# Generated by Django 5.0.6 on 2024-06-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_holdinghistory_buy_date_holdinghistory_buy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
